SubsCon= {'MAC_CON_011'...
'MAC_CON_013'...
'MAC_CON_016'...
'MAC_CON_018'...
'MAC_CON_019'...
'MAC_CON_024'...
'MAC_CON_025'...
'MAC_CON_026'...
'MAC_CON_08'...
'MAC_CON_09'};

Subs = {  'MAC_DE_011'...
'MAC_DE_013'...
'MAC_DE_016'...
'MAC_DE_018'...
'MAC_DE_019'...
'MAC_DE_024'...
'MAC_DE_025'...
'MAC_DE_026'...
'MAC_DE_08'...
'MAC_DE_09' };

for x = 1:length(Subs)
    macd = ['lh.' Subs{x} '.lh.thickness'];
    macdCON = ['lh.' SubsCon{x} '.lh.thickness'];
    thickmd = read_curv (macd);
    thick = read_curv (macdCON);
    withindiff = thick - thickmd;
    withindiff(isnan(withindiff)) = 0;
    storeConMinusMD(:,x) = withindiff;
end

storeold = storeConMinusMD;

storeConMinusMD = storeConMinusMD';
storeConMinusMD(1,:)
h(isnan(h)) = 0 ;

[h,p,ci,stats] = ttest(storeConMinusMD');
 h(isnan(h)) = 0 ;
 
 storemean = mean(storeConMinusMD');
 storettestmean = (storemean .* h);
 
    
 write_curv('ttest_diff_macD',storettestmean, 163842)
 
 
 for x = 1:length(Subs)
 eval(['! mri_surf2surf --srcsubject ' SubsCon{x} ' --srcsurfval thickness  --src_type curv --trgsubject ' 'fsaverage' ' --trgsurfval ' SubsCon{x} '.lh.thickness'  ' --trg_type curv  --hemi lh']) ;
 end   
    
    
    